SELECT * FROM employee;
SELECT * FROM bonus;
SELECT * FROM department;
SELECT * FROM salgrade;

SELECT ENAME FROM employee;
SELECT ENO, ENAME, SALARY FROM employee;
SELECT ENAME, SALARY FROM employee;
SELECT SALARY*12 FROM employee;
SELECT ENAME, SALARY / 100 FROM employee;
SELECT ENAME, SALARY + 100 FROM employee;
SELECT ENAME, SALARY - 100 FROM employee;

SELECT ENAME, SALARY, SALARY*12 AS 연봉 FROM employee;
SELECT ENAME, SALARY, SALARY*12 연봉 FROM employee;
-- 한 줄 주석
/* 
  여러 줄 주석
*/
SELECT * FROM employee;
SELECT ENAME, SALARY, COMMISSION, SALARY + COMMISSION FROM employee;
SELECT ENAME, SALARY, COMMISSION, SALARY + NVL(COMMISSION, 0) AS 결과 FROM employee;

SELECT DISTINCT DNO FROM employee;

SELECT 
    DISTINCT (DNO) 
FROM employee;

